#
###################################
# Site wide configuration
####################################
#
title: Segun
email: segunfamisa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey, I'm an android developer, I love to create :)
#url: http://renyuanz.github.io/leonids # the base hostname & protocol for your site
url: http://segunfamisa.github.io

#
###################################
# Jekyll configuration
####################################
#
markdown:    kramdown
highlighter: pygments
excerpt_separator: <!--more-->
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Jekyll configuration
####################################
#
owner:
  name: Segun
  avatar: avatar.jpg
  bio: "Do. Something. Awesome."
  email: segunfamisa@gmail.com
  disqus-shortname: segunfamisa-site
  twitter: segunfamisa #username
  facebook: segunfamisa #username
  google:
    plus: OluwasegunFamisa #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: segunfamisa #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: segunfamisa #username
  xing: #username
  instagram: segunfamisa #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
