#
###################################
# Site wide configuration
####################################
#
title:       "Leonids Jekyll theme"
description: "Clean Jekyll blog theme called Leonids."
url:         # the base hostname & protocol for your site

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Your name
  avatar: avatar.jpg
  job: "Your job"
  bio: "Write about yourself"
  email:
  disqus-shortname:
  twitter:
  facebook:
  google:
    plus:
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
